  name: Playwright Python CI
  on:
    workflow_dispatch:
  jobs:
    build:
      runs-on: ubuntu-latest

      
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r wymagania.txt
              playwright install

        - name: Create screenshot directory
          run: |
            mkdir screenshot
        - name: Run tests
          run: |
            pytest
        - name: Upload screenshot
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: screenshot
            path: screenshot
